#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat May 27 14:56:24 2023

@author: melvinzhang
"""

import pandas as pd
import datetime
df_csv = pd.read_excel('/Users/melvinzhang/Documents/IBEB ERASMUS SCHOOL OF ECONOMICS/B3/Financial Economics/Thesis/Data/IV/NYSE Volume Daily Data.xlsx')
df_csv['Trade Date'] = pd.to_datetime(df_csv['Trade Date']).dt.strftime('%Y-%m-%d')
df_csv['Trade Date'] = df_csv['Trade Date']
df_csv.set_index('Trade Date', inplace=True)
df_excel = pd.read_excel('/Users/melvinzhang/Documents/IBEB ERASMUS SCHOOL OF ECONOMICS/B3/Financial Economics/Thesis/Data/WTH/FULL DATA SET/wth SVI API data.xlsx')
# vix_list = df_csv['CLOSE'].to_list()
# vix_date = df.csv['DATE'].to_list()
date_list = df_excel['ipodate'].to_list()
volume = []
for i in date_list:
    volume.append(df_csv.loc[i,'Consolidated Tape C'])
df_excel['tv_nyse_c'] = volume
    
df_excel.to_excel('/Users/melvinzhang/Documents/IBEB ERASMUS SCHOOL OF ECONOMICS/B3/Financial Economics/Thesis/Data/WTH/FULL DATA SET/wth SVI API data.xlsx')


